from .depth_completion_agent import DepthCompletionAgent
from .mul_model_dc_agent import MultiModelDepthCompletionAgent
from .self_Attention_agent import GatedConvSkipConnectionAgent as GCSC
from .resnet18_Baseline_agent import ResNet18SkipConnectionAgent as R18SC
from .self_Attention_BC_agent import BoundaryConsistencyUNetAgent as BCU
